export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    members: "Members",
    income: "Income / Sales",
    expenses: "Expenses / Purchases",
    subscriptions: "Subscriptions",
    reports: "Reports",
    settings: "Settings",
    logout: "Logout",
    total_income: "Total Income",
    total_expense: "Total Expense",
    balance: "Balance",
    active_members: "Active Members",
    active_subs: "Active Subscriptions",
    recent_transactions: "Recent Transactions",
    add_member: "Add Member",
    add_income: "Add Income",
    add_expense: "Add Expense",
    name: "Name",
    tamil_name: "Tamil Name",
    phone: "Phone",
    email: "Email",
    category: "Category",
    amount: "Amount",
    date: "Date",
    payment_mode: "Payment Mode",
    actions: "Actions",
    save: "Save",
    cancel: "Cancel",
    print: "Print",
    export: "Export",
    invoice_no: "Invoice No",
    member_code: "Member Code",
    address: "Address",
    family_details: "Family Details",
    membership_type: "Membership Type",
    joined_date: "Joined Date",
    vendor: "Vendor",
    items: "Items",
    gst: "GST",
    notes: "Notes",
    search: "Search",
    filter: "Filter",
    language: "Language",
    church_profile: "Church Profile",
    financial_year: "Financial Year",
    currency: "Currency",
    tithe: "Tithe",
    offering: "Offering",
    event: "Event",
    book_sale: "Book Sale",
    maintenance: "Maintenance",
    salary: "Salary",
    utility: "Utility",
    other: "Other",
    edit_member: "Edit Member",
    confirm_delete_member: "Are you sure you want to delete this member?",
    delete: "Delete",
    edit: "Edit",
    saving: "Saving...",
    cash_counter: "Cash Counter",
    reset: "Reset",
    confirm_reset: "Are you sure you want to reset all counts?",
    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    password_reset_success: "Password updated successfully!",
    password_reset_default: "Reset to Default Password",
    confirm_password_reset: "Are you sure you want to reset the password to 'admin123'?",
    forgot_password: "Forgot Password?",
    enter_email_otp: "Enter your registered email to receive an OTP",
    send_otp: "Send OTP",
    otp_sent: "OTP sent to your email!",
    enter_otp: "Enter OTP",
    verify_otp: "Verify & Reset",
    new_password_placeholder: "Enter new password",
    otp_placeholder: "6-digit OTP",
    notepad: "Notepad",
    add_note: "Add Note",
    edit_note: "Edit Note",
    prayer: "Prayer",
    auction: "Auction",
    materials: "Materials",
    user_name: "User Name",
    mobile: "Mobile Number",
    content: "Content / Details",
    confirm_delete_note: "Are you sure you want to delete this note?",
    status: "Status",
    pending: "Pending",
    paid: "Paid",
    income_analysis: "Income Analysis",
    top_contributors: "Top Contributors",
    total_contribution: "Total Contribution",
    transaction_count: "No. of Transactions",
    rank: "Rank"
  },
  ta: {
    dashboard: "முகப்பு",
    members: "உறுப்பினர்கள்",
    income: "வருமானம் / விற்பனை",
    expenses: "செலவுகள் / கொள்முதல்",
    subscriptions: "சந்தாக்கள்",
    reports: "அறிக்கைகள்",
    settings: "அமைப்புகள்",
    logout: "வெளியேறு",
    total_income: "மொத்த வருமானம்",
    total_expense: "மொத்த செலவு",
    balance: "இருப்பு",
    active_members: "செயலில் உள்ள உறுப்பினர்கள்",
    active_subs: "செயலில் உள்ள சந்தாக்கள்",
    recent_transactions: "சமீபத்திய பரிவர்த்தனைகள்",
    add_member: "உறுப்பினரைச் சேர்",
    add_income: "வருமானத்தைச் சேர்",
    add_expense: "செலவைச் சேர்",
    name: "பெயர்",
    tamil_name: "தமிழ் பெயர்",
    phone: "தொலைபேசி",
    email: "மின்னஞ்சல்",
    category: "வகை",
    amount: "தொகை",
    date: "தேதி",
    payment_mode: "பணம் செலுத்தும் முறை",
    actions: "செயல்கள்",
    save: "சேமி",
    cancel: "ரத்து செய்",
    print: "அச்சிடு",
    export: "ஏற்றுமதி",
    invoice_no: "இன்வாய்ஸ் எண்",
    member_code: "உறுப்பினர் குறியீடு",
    address: "முகவரி",
    family_details: "குடும்ப விவரங்கள்",
    membership_type: "உறுப்பினர் வகை",
    joined_date: "சேர்ந்த தேதி",
    vendor: "விற்பனையாளர்",
    items: "பொருட்கள்",
    gst: "ஜிஎஸ்டி",
    notes: "குறிப்புகள்",
    search: "தேடு",
    filter: "வடிகட்டி",
    language: "மொழி",
    church_profile: "தேவாலய விவரம்",
    financial_year: "நிதியாண்டு",
    currency: "நாணயம்",
    tithe: "தசமபாகம்",
    offering: "காணிக்கை",
    event: "நிகழ்ச்சி",
    book_sale: "புத்தக விற்பனை",
    maintenance: "பராமரிப்பு",
    salary: "சம்பளம்",
    utility: "பயன்பாடு",
    other: "மற்றவை",
    edit_member: "உறுப்பினர் விவரத்தை மாற்றவும்",
    confirm_delete_member: "இந்த உறுப்பினரை நீக்க விரும்புகிறீர்களா?",
    delete: "நீக்கு",
    edit: "திருத்து",
    saving: "சேமிக்கப்படுகிறது...",
    cash_counter: "பணக் கணக்கீடு",
    reset: "மீட்டமை",
    confirm_reset: "அனைத்து எண்ணிக்கையையும் மீட்டமைக்க விரும்புகிறீர்களா?",
    change_password: "கடவுச்சொல்லை மாற்றவும்",
    current_password: "தற்போதைய கடவுச்சொல்",
    new_password: "புதிய கடவுச்சொல்",
    confirm_password: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    password_reset_success: "கடவுச்சொல் வெற்றிகரமாக மாற்றப்பட்டது!",
    password_reset_default: "இயல்புநிலை கடவுச்சொல்லுக்கு மீட்டமைக்கவும்",
    confirm_password_reset: "கடவுச்சொல்லை 'admin123' க்கு மீட்டமைக்க விரும்புகிறீர்களா?",
    forgot_password: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    enter_email_otp: "OTP பெற உங்கள் பதிவு செய்யப்பட்ட மின்னஞ்சலை உள்ளிடவும்",
    send_otp: "OTP அனுப்பு",
    otp_sent: "உங்கள் மின்னஞ்சலுக்கு OTP அனுப்பப்பட்டது!",
    enter_otp: "OTP ஐ உள்ளிடவும்",
    verify_otp: "சரிபார்த்து மீட்டமைக்கவும்",
    new_password_placeholder: "புதிய கடவுச்சொல்லை உள்ளிடவும்",
    otp_placeholder: "6-இலக்க OTP",
    notepad: "நோட்பேட்",
    add_note: "குறிப்பைச் சேர்",
    edit_note: "குறிப்பைத் திருத்து",
    prayer: "ஜெபம்",
    auction: "ஏலம்",
    materials: "பெறப்பட்ட பொருட்கள்",
    user_name: "பயனர் பெயர்",
    mobile: "கைபேசி எண்",
    content: "விவரங்கள்",
    confirm_delete_note: "இந்த குறிப்பை நீக்க விரும்புகிறீர்களா?",
    status: "நிலை",
    pending: "நிலுவையில் உள்ளது",
    paid: "செலுத்தப்பட்டது",
    income_analysis: "வருமான ஆய்வு",
    top_contributors: "அதிக வருமானம் தரும் உறுப்பினர்கள்",
    total_contribution: "மொத்த பங்களிப்பு",
    transaction_count: "பரிவர்த்தனைகளின் எண்ணிக்கை",
    rank: "வரிசை"
  }
};
